### PR TITLE
Fix nullability and reflection field name

### LINKED ISSUE #28: Crash when launching app with latest update
Hi!

With the latest update, the app crashes as soon as it starts. If I switch back to the old library, it works as it should. I've tried to rebuild all, but still same problem.

My project was migrated to AndroidX some months ago, so that should not be any issue. Running on Android 7 on an emulator. (My project doesn't use any kotlin code, if that matters.) I'm using this library together with Calligraphy3.

Here is the stack trace:

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.the.app/com.the.app.activities.MainActivity}: android.view.InflateException: Binary XML file line #24: Binary XML file line #24: Error inflating class LinearLayout
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2646)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6077)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)
     Caused by: android.view.InflateException: Binary XML file line #24: Binary XML file line #24: Error inflating class LinearLayout
     Caused by: android.view.InflateException: Binary XML file line #24: Error inflating class LinearLayout
     Caused by: java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter parent
        at io.github.inflationx.viewpump.ViewPumpLayoutInflater.onCreateView(ViewPumpLayoutInflater.kt)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:785)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:495)
        at io.github.inflationx.viewpump.ViewPumpLayoutInflater.inflate(ViewPumpLayoutInflater.kt:54)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
        at io.github.inflationx.viewpump.ViewPumpLayoutInflater.inflate(ViewPumpLayoutInflater.kt:45)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:377)
        at com.android.internal.policy.DecorView.onResourcesLoaded(DecorView.java:1776)
        at com.android.internal.policy.PhoneWindow.generateLayout(PhoneWindow.java:2613)
        at com.android.internal.policy.PhoneWindow.installDecor(PhoneWindow.java:2686)
        at com.android.internal.policy.PhoneWindow.getDecorView(PhoneWindow.java:2049)
        at androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor(AppCompatDelegateImpl.java:575)
        at androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor(AppCompatDelegateImpl.java:518)
        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:466)
        at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
        at com.the.app.activities.MainActivity.onCreate(MainActivity.java:270)
        at android.app.Activity.performCreate(Activity.java:6662)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2599)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6077)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)
```

### PR DESCRIPTION
**Pull request by jbarr21**
Resolves #28

### CODE REVIEW

File: viewpump/src/main/java/io/github/inflationx/viewpump/ViewPumpLayoutInflater.kt [hunk 1]
```diff
@@ -374,7 +374,7 @@ internal class ViewPumpLayoutInflater : LayoutInflater, ViewPumpActivityFactory
 
     private val CLASS_PREFIX_LIST = setOf("android.widget.", "android.webkit.")
     private val CONSTRUCTOR_ARGS_FIELD: Field by lazy {
-      requireNotNull(LayoutInflater::class.java.getDeclaredField("CONSTRUCTOR_ARGS_FIELD")) {
```
Comment (chrisjenx) [inline viewpump/src/main/java/io/github/inflationx/viewpump/ViewPumpLayoutInflater.kt]: Eep that could have been bad!
